### ISSUE TITLE
feature request: register work on past days

### ISSUE THREAD

**Issue by nils-a-r** [jhthorsen/app-tt#1]
Great little tool!!

I just want to be able to do such as this when I have forgot to register my activities.
tt start 2015-10-02T08:00 --project foo --tag bar
tt stop 2015-10-02T09:30 --project foo --tag bar

**Comment by jhthorsen** [comment]
You can do this with the "register" action:

```
$ tt register --help

This command is used to import data from other sources. "project-name" default to
"-p" or current git project, "some description" default to "-d" and tags can be
specified by -t foo -t bar

$ tt register 2010-01-21T18:50:00  2010-01-21T19:20:00 "project-name" "some description" "foo,bar"
$ echo "2010-01-21T18:50:00\t2010-01-21T19:20:00\tproject-name\tsome description\tfoo,bar" | tt register
```

So I think the input above becomes:

```
tt register 2015-10-02T08:00 2015-10-02T09:30 -p foo -t bar
```

**Comment by nils-a-r** [comment]
I hadn't tried "register" but the action doesn't seem to support -p and -t options. I get the same help output as you pasted above when trying that.
And then the order of text fields must be <project>, <description>, <tags>..

tt register does what I need but you may look at the small bugs :)

**Comment by jhthorsen** [comment]
@nils-a-r: Finally "register" supports -t and -p 🙈
